import { daysFromNowZoned } from './dates.js'

const IST = 'Asia/Kolkata'
const GMT = 'Europe/London'
const EST = 'America/New_York'
const SGT = 'Asia/Singapore'
const GST = 'Asia/Dubai'

const hoursAgo = (h) => Date.now() - h * 3600 * 1000

/**
 * Isolated Upcoming fixtures. Not imported by src/data.js.
 * Sample copy for UI; not a live intelligence feed.
 */
export const UPCOMING_DEMO_NOTE =
  'Demo fixtures · not live feed data. Following saves on this device only.'

export const UPCOMING_DEMO_EVENTS = [
  {
    id: 'demo-blr-roads',
    dataOrigin: 'demo',
    title: 'Road restrictions around the convention district',
    place: 'Bengaluru, Karnataka, India',
    locationKey: 'Bengaluru',
    coords: [77.5946, 12.9716],
    timezone: IST,
    startsAt: daysFromNowZoned(2, 8, 0, IST),
    endsAt: daysFromNowZoned(2, 18, 0, IST),
    timeConfirmed: true,
    eventStatus: 'scheduled',
    severity: 'high',
    category: 'geopolitical',
    alertType: 'intelligence',
    expectedImpact: {
      disruption: 'Arterial closures and last-mile delay around the convention district.',
      activities: ['Staff commute', 'Visitor arrivals', 'Courier windows'],
    },
    exposures: [
      {
        assetId: null,
        assetName: 'Bengaluru Office',
        evidence: 'potential',
        reason: 'Access road intersects the notified restriction area.',
      },
    ],
    preparation: {
      kind: 'suggested',
      items: [
        'Shift on-site arrivals outside 08:00–18:00 IST.',
        'Brief drivers on alternate routes around the convention district.',
      ],
    },
    sources: [
      {
        title: 'Traffic police advisory (sample)',
        url: 'https://example.invalid/blr-roads',
        publishedAt: hoursAgo(20),
      },
    ],
    lastVerifiedAt: hoursAgo(2),
    updatedAt: hoursAgo(0.75),
    history: [
      { at: hoursAgo(20), kind: 'scheduled', text: 'Window published for a single-day restriction.' },
      { at: hoursAgo(0.75), kind: 'advisory', text: 'Police confirmed the same window; no extension filed.' },
    ],
    summary: 'Licensed restrictions. Time confirmed. Sample fixture, not a live feed.',
  },
  {
    id: 'demo-pune-march',
    dataOrigin: 'demo',
    title: 'Student march notified for FC Road — weekend window',
    place: 'Pune, Maharashtra, India',
    locationKey: 'Pune',
    coords: [73.841, 18.531],
    timezone: IST,
    startsAt: daysFromNowZoned(1, 9, 0, IST),
    endsAt: daysFromNowZoned(1, 14, 0, IST),
    timeConfirmed: true,
    eventStatus: 'scheduled',
    severity: 'low',
    category: 'geopolitical',
    alertType: 'intelligence',
    expectedImpact: {
      disruption: 'Procession traffic and temporary access control on FC Road.',
      activities: ['Office access', 'Local commuting'],
    },
    exposures: [
      {
        assetId: 'ast-pune',
        assetName: 'Pune Office',
        evidence: 'potential',
        reason: 'Licensed route passes about 2.1 km from the office — traffic and access, not violence.',
      },
    ],
    preparation: {
      kind: 'suggested',
      items: ['Allow extra commute time after 09:00 IST.', 'Keep visitor parking off FC Road for the window.'],
    },
    sources: [{ title: 'Reuters (sample fixture)', url: 'https://www.reuters.com/world/', publishedAt: hoursAgo(9) }],
    lastVerifiedAt: hoursAgo(4),
    updatedAt: hoursAgo(4),
    history: [{ at: hoursAgo(9), kind: 'scheduled', text: 'Police procession licence posted.' }],
    summary: 'Low violence history; traffic is the issue.',
  },
  {
    id: 'demo-lon-rail',
    dataOrigin: 'demo',
    title: 'Rail union overtime ban — 48-hour disruption from Friday',
    place: 'London, United Kingdom',
    locationKey: 'London',
    coords: [-0.12, 51.51],
    timezone: GMT,
    startsAt: daysFromNowZoned(4, 0, 0, GMT),
    endsAt: daysFromNowZoned(5, 23, 59, GMT),
    timeConfirmed: true,
    eventStatus: 'scheduled',
    severity: 'medium',
    category: 'geopolitical',
    alertType: 'intelligence',
    expectedImpact: {
      disruption: 'Reduced rail frequency and longer last-mile times into central London.',
      activities: ['Office commute', 'Client meetings'],
    },
    exposures: [
      {
        assetId: 'ast-lon',
        assetName: 'London Office',
        evidence: 'potential',
        reason: 'Commute impact for the office; the facility itself is not a target.',
      },
    ],
    preparation: {
      kind: 'analyst',
      items: ['Offer remote attendance for Friday meetings.', 'Do not treat the building as a protest site.'],
    },
    sources: [{ title: 'Reuters (sample fixture)', url: 'https://www.reuters.com/world/', publishedAt: hoursAgo(6) }],
    lastVerifiedAt: hoursAgo(3),
    updatedAt: hoursAgo(3),
    history: [{ at: hoursAgo(6), kind: 'scheduled', text: '48-hour action window confirmed by the union notice.' }],
    summary: 'Multi-day industrial action. One record covering both days.',
  },
  {
    id: 'demo-che-cyclone',
    dataOrigin: 'demo',
    title: 'Bay cyclone bands: high wind and surge watch for Chennai coast',
    place: 'Chennai, Tamil Nadu, India',
    locationKey: 'Chennai',
    coords: [80.29, 13.1],
    timezone: IST,
    startsAt: daysFromNowZoned(0, 6, 0, IST),
    endsAt: daysFromNowZoned(3, 20, 0, IST),
    timeConfirmed: true,
    eventStatus: 'scheduled',
    severity: 'high',
    category: 'environmental',
    alertType: 'informative',
    expectedImpact: {
      disruption: 'Port slowdowns, perimeter drainage load, and likely night-shift cancellations.',
      activities: ['Plant operations', 'Contractor night shifts', 'Port receipts'],
    },
    exposures: [
      {
        assetId: 'ast-che',
        assetName: 'Chennai Plant',
        evidence: 'potential',
        reason: 'Coastal watch covers the plant drainage basin through the multi-day window.',
      },
    ],
    preparation: {
      kind: 'suggested',
      items: ['Inspect plant perimeter drainage.', 'Plan contractor night-shift cancellation if orange is held.'],
    },
    sources: [{ title: 'IMD bulletin (sample)', url: 'https://mausam.imd.gov.in/', publishedAt: hoursAgo(8) }],
    lastVerifiedAt: hoursAgo(1.5),
    updatedAt: hoursAgo(1.5),
    history: [
      { at: hoursAgo(8), kind: 'scheduled', text: 'Yellow watch posted.' },
      { at: hoursAgo(1.5), kind: 'advisory', text: 'Bands still tracking the northern Tamil Nadu coast.' },
    ],
    summary: 'Ongoing multi-day weather watch shown once, not cloned per day.',
  },
  {
    id: 'demo-nyc-tide',
    dataOrigin: 'demo',
    title: 'Coastal flood watch — Midtown and Columbus Circle',
    place: 'Manhattan, New York, USA',
    locationKey: 'New York',
    coords: [-73.984, 40.7672],
    timezone: EST,
    startsAt: daysFromNowZoned(1, 16, 0, EST),
    endsAt: daysFromNowZoned(1, 22, 0, EST),
    timeConfirmed: true,
    eventStatus: 'scheduled',
    severity: 'medium',
    category: 'environmental',
    alertType: 'informative',
    expectedImpact: {
      disruption: 'Pedestrian slowdown around Deutsche Bank Center on the next tide cycle.',
      activities: ['HQ access', 'Street-level arrivals'],
    },
    exposures: [
      {
        assetId: 'db-nyc',
        assetName: 'Deutsche Bank · New York',
        evidence: 'potential',
        reason: 'Watch includes the Columbus Circle sidewalk network at the HQ fence.',
      },
    ],
    preparation: { kind: 'suggested', items: ['Allow extra time for street-level access during the tide window.'] },
    sources: [{ title: 'NWS (sample fixture)', url: 'https://www.weather.gov/', publishedAt: hoursAgo(3) }],
    lastVerifiedAt: hoursAgo(3),
    updatedAt: hoursAgo(3),
    history: [{ at: hoursAgo(3), kind: 'scheduled', text: 'Coastal flood watch issued for the next tide cycle.' }],
    summary: 'Forecast tide window only.',
  },
  {
    id: 'demo-mum-bandh',
    dataOrigin: 'demo',
    title: 'City-wide protest call — time window not confirmed',
    place: 'Mumbai, Maharashtra, India',
    locationKey: 'Mumbai',
    coords: [72.869, 19.089],
    timezone: IST,
    startsAt: daysFromNowZoned(6, 0, 0, IST),
    endsAt: null,
    timeConfirmed: false,
    eventStatus: 'tentative',
    severity: 'medium',
    category: 'geopolitical',
    alertType: 'intelligence',
    expectedImpact: {
      disruption: 'Possible arterial slowdowns if the call firms up; hours not filed.',
      activities: ['Warehouse gate', 'Last-mile trucks'],
    },
    exposures: [
      {
        assetId: 'ast-mum-wh',
        assetName: 'Mumbai Warehouse',
        evidence: 'potential',
        reason: 'If the bandh is confirmed, last-mile trucks at the warehouse gate are typically delayed.',
      },
    ],
    preparation: { kind: 'suggested', items: ['Hold a same-day go/no-go for outbound trucks until hours are posted.'] },
    sources: [{ title: 'Local notice (sample)', url: null, publishedAt: hoursAgo(12) }],
    lastVerifiedAt: hoursAgo(12),
    updatedAt: hoursAgo(5),
    history: [{ at: hoursAgo(12), kind: 'advisory', text: 'Call circulated; police have not posted hours.' }],
    summary: 'Tentative. Time not confirmed.',
  },
  {
    id: 'demo-ggm-cancelled',
    dataOrigin: 'demo',
    title: 'Campus perimeter drill — cancelled',
    place: 'Gurugram, Haryana, India',
    locationKey: 'Gurugram',
    coords: [77.072, 28.47],
    timezone: IST,
    startsAt: daysFromNowZoned(3, 10, 0, IST),
    endsAt: daysFromNowZoned(3, 12, 0, IST),
    timeConfirmed: true,
    eventStatus: 'cancelled',
    severity: 'low',
    category: 'security',
    alertType: 'intelligence',
    expectedImpact: {
      disruption: 'Drill will not run. No expected access change.',
      activities: [],
    },
    exposures: [],
    preparation: null,
    sources: [{ title: 'Campus security note (sample)', url: null, publishedAt: hoursAgo(30) }],
    lastVerifiedAt: hoursAgo(6),
    updatedAt: hoursAgo(6),
    history: [
      { at: hoursAgo(30), kind: 'scheduled', text: 'Perimeter drill listed for mid-morning.' },
      { at: hoursAgo(6), kind: 'cancelled', text: 'Drill cancelled; resume normal access.' },
    ],
    summary: 'Cancelled — kept in the agenda, excluded from active counts.',
  },
  {
    id: 'demo-dxb-postponed',
    dataOrigin: 'demo',
    title: 'Sheikh Zayed underpass works — postponed',
    place: 'Dubai, UAE',
    locationKey: 'Dubai',
    coords: [55.274, 25.197],
    timezone: GST,
    startsAt: daysFromNowZoned(8, 22, 0, GST),
    endsAt: daysFromNowZoned(9, 5, 0, GST),
    timeConfirmed: true,
    eventStatus: 'postponed',
    severity: 'medium',
    category: 'environmental',
    alertType: 'informative',
    expectedImpact: {
      disruption: 'Night gate delays if the works window is reissued.',
      activities: ['Logistics gate'],
    },
    exposures: [
      {
        assetId: 'ast-dxb',
        assetName: 'Dubai Logistics',
        evidence: 'potential',
        reason: 'Underpass works historically pond the last-mile approach to the logistics gate.',
      },
    ],
    preparation: { kind: 'suggested', items: ['Wait for the reissued night window before changing gate staffing.'] },
    sources: [{ title: 'RTA notice (sample)', url: null, publishedAt: hoursAgo(40) }],
    lastVerifiedAt: hoursAgo(10),
    updatedAt: hoursAgo(10),
    history: [
      { at: hoursAgo(40), kind: 'scheduled', text: 'Night works window posted.' },
      { at: hoursAgo(10), kind: 'postponed', text: 'Works postponed; replacement night not filed.' },
    ],
    summary: 'Postponed night works.',
  },
  {
    id: 'demo-sin-haze',
    dataOrigin: 'demo',
    title: 'Transboundary haze: outdoor work advisory window',
    place: 'Singapore',
    locationKey: 'Singapore',
    coords: [103.82, 1.36],
    timezone: SGT,
    startsAt: daysFromNowZoned(12, 7, 0, SGT),
    endsAt: daysFromNowZoned(14, 19, 0, SGT),
    timeConfirmed: true,
    eventStatus: 'scheduled',
    severity: 'low',
    category: 'environmental',
    alertType: 'informative',
    expectedImpact: {
      disruption: 'Outdoor holds if PSI turns unhealthy; hub indoor operations stay normal.',
      activities: ['Outdoor work', 'Hub operations'],
    },
    exposures: [
      {
        assetId: 'ast-sin',
        assetName: 'Singapore Hub',
        evidence: 'potential',
        reason: 'Advisory covers outdoor contractor work at the hub; indoor floors are unaffected in the sample note.',
      },
    ],
    preparation: { kind: 'suggested', items: ['Keep outdoor contractor work on a PSI trigger, not a blanket stop.'] },
    sources: [{ title: 'NEA (sample fixture)', url: 'https://www.nea.gov.sg/', publishedAt: hoursAgo(18) }],
    lastVerifiedAt: hoursAgo(8),
    updatedAt: hoursAgo(8),
    history: [{ at: hoursAgo(18), kind: 'scheduled', text: 'Three-day outdoor advisory window posted.' }],
    summary: 'Low-severity environmental advisory.',
  },
  {
    id: 'demo-fra-march',
    dataOrigin: 'demo',
    title: 'Climate march on Taunusanlage — Bankenviertel traffic held',
    place: 'Frankfurt am Main, Germany',
    locationKey: 'Frankfurt',
    coords: [8.6752, 50.1124],
    timezone: 'Europe/Berlin',
    startsAt: daysFromNowZoned(18, 11, 0, 'Europe/Berlin'),
    endsAt: daysFromNowZoned(18, 16, 0, 'Europe/Berlin'),
    timeConfirmed: true,
    eventStatus: 'scheduled',
    severity: 'medium',
    category: 'geopolitical',
    alertType: 'intelligence',
    expectedImpact: {
      disruption: 'Lane closures on Mainzer Landstraße during the licensed procession.',
      activities: ['HQ access', 'Taxi drop-off'],
    },
    exposures: [
      {
        assetId: 'db-fra',
        assetName: 'Deutsche Bank HQ · Frankfurt',
        evidence: 'potential',
        reason: 'Frankfurt HQ sits inside the Bankenviertel disruption radius for the march window.',
      },
    ],
    preparation: { kind: 'suggested', items: ['Reroute HQ arrivals off Mainzer Landstraße for the afternoon window.'] },
    sources: [{ title: 'Police notice (sample)', url: null, publishedAt: hoursAgo(24) }],
    lastVerifiedAt: hoursAgo(7),
    updatedAt: hoursAgo(7),
    history: [{ at: hoursAgo(24), kind: 'scheduled', text: 'Licensed procession posted.' }],
    summary: 'Scheduled civil march.',
  },
  {
    id: 'demo-no-geo',
    dataOrigin: 'demo',
    title: 'Industry association travel advisory — location not mapped',
    place: 'National, India',
    locationKey: 'National',
    coords: null,
    timezone: IST,
    startsAt: daysFromNowZoned(21, 9, 0, IST),
    endsAt: daysFromNowZoned(21, 18, 0, IST),
    timeConfirmed: true,
    eventStatus: 'scheduled',
    severity: 'low',
    category: 'geopolitical',
    alertType: 'intelligence',
    expectedImpact: {
      disruption: 'General travel caution; no site geometry in this record.',
      activities: ['Staff travel'],
    },
    exposures: [],
    preparation: { kind: 'suggested', items: ['Treat as awareness only until a city list is filed.'] },
    sources: [{ title: 'Association note (sample)', url: null, publishedAt: hoursAgo(2) }],
    lastVerifiedAt: hoursAgo(2),
    updatedAt: hoursAgo(2),
    history: [{ at: hoursAgo(2), kind: 'advisory', text: 'National note without coordinates.' }],
    summary: 'No map geometry in this fixture.',
  },
  {
    id: 'demo-q2-port',
    dataOrigin: 'demo',
    title: 'Planned Nhava Sheva berth maintenance',
    place: 'Nhava Sheva, Maharashtra, India',
    locationKey: 'Nhava Sheva',
    coords: [72.95, 18.95],
    timezone: IST,
    startsAt: daysFromNowZoned(55, 6, 0, IST),
    endsAt: daysFromNowZoned(57, 18, 0, IST),
    timeConfirmed: true,
    eventStatus: 'scheduled',
    severity: 'medium',
    category: 'environmental',
    alertType: 'informative',
    expectedImpact: {
      disruption: 'Berth outage may back up inbound containers by 24–48 hours.',
      activities: ['Import receipts', 'Warehouse inbound'],
    },
    exposures: [
      {
        assetId: 'ast-mum-wh',
        assetName: 'Mumbai Warehouse',
        evidence: 'potential',
        reason: 'Inbound boxes for the warehouse typically clear Nhava Sheva; a berth outage can slip receipts.',
      },
    ],
    preparation: { kind: 'suggested', items: ['Pull critical SKUs forward before the maintenance window.'] },
    sources: [{ title: 'Port circular (sample)', url: null, publishedAt: hoursAgo(48) }],
    lastVerifiedAt: hoursAgo(20),
    updatedAt: hoursAgo(20),
    history: [{ at: hoursAgo(48), kind: 'scheduled', text: 'Three-day berth maintenance listed.' }],
    summary: 'Far-window item for the 90-day week grouping.',
  },
]
