export const DEUTSCHE_HQ = [
  {
    id: 'db-fra',
    org: 'deutsche-bank',
    name: 'Deutsche Bank HQ · Frankfurt',
    type: 'HQ',
    city: 'Frankfurt',
    country: 'Germany',
    address: 'Taunusanlage 12',
    coords: [8.6719, 50.1136],
    criticality: 'high',
    radiusKm: 25,
  },
  {
    id: 'db-lon',
    org: 'deutsche-bank',
    name: 'Deutsche Bank · London',
    type: 'HQ',
    city: 'London',
    country: 'United Kingdom',
    address: '21 Moorfields',
    coords: [-0.0889, 51.5183],
    criticality: 'high',
    radiusKm: 20,
  },
  {
    id: 'db-nyc',
    org: 'deutsche-bank',
    name: 'Deutsche Bank · New York',
    type: 'HQ',
    city: 'New York',
    country: 'United States',
    address: '1 Columbus Circle',
    coords: [-73.9829, 40.7685],
    criticality: 'high',
    radiusKm: 20,
  },
  {
    id: 'db-sin',
    org: 'deutsche-bank',
    name: 'Deutsche Bank · Singapore',
    type: 'HQ',
    city: 'Singapore',
    country: 'Singapore',
    address: 'One Raffles Quay',
    coords: [103.8515, 1.2808],
    criticality: 'high',
    radiusKm: 15,
  },
  {
    id: 'db-hkg',
    org: 'deutsche-bank',
    name: 'Deutsche Bank · Hong Kong',
    type: 'HQ',
    city: 'Hong Kong',
    country: 'China',
    address: 'ICC, 1 Austin Road West',
    coords: [114.1602, 22.3033],
    criticality: 'medium',
    radiusKm: 15,
  },
  {
    id: 'db-tyo',
    org: 'deutsche-bank',
    name: 'Deutsche Bank · Tokyo',
    type: 'HQ',
    city: 'Tokyo',
    country: 'Japan',
    address: 'Sanno Park Tower',
    coords: [139.7384, 35.6731],
    criticality: 'medium',
    radiusKm: 20,
  },
  {
    id: 'db-mum',
    org: 'deutsche-bank',
    name: 'Deutsche Bank · Mumbai',
    type: 'HQ',
    city: 'Mumbai',
    country: 'India',
    address: 'Bandra Kurla Complex',
    coords: [72.8636, 19.0612],
    criticality: 'high',
    radiusKm: 20,
  },
  {
    id: 'db-dxb',
    org: 'deutsche-bank',
    name: 'Deutsche Bank · Dubai',
    type: 'HQ',
    city: 'Dubai',
    country: 'UAE',
    address: 'DIFC',
    coords: [55.2796, 25.2144],
    criticality: 'medium',
    radiusKm: 15,
  },
  {
    id: 'db-syd',
    org: 'deutsche-bank',
    name: 'Deutsche Bank · Sydney',
    type: 'HQ',
    city: 'Sydney',
    country: 'Australia',
    address: '126 Phillip Street',
    coords: [151.2113, -33.8675],
    criticality: 'medium',
    radiusKm: 15,
  },
]

export const ASSETS = [
  {
    id: 'ast-mum-wh',
    name: 'Mumbai Warehouse',
    type: 'Warehouse',
    city: 'Mumbai',
    country: 'India',
    coords: [72.8777, 19.076],
    criticality: 'high',
    radiusKm: 25,
  },
  {
    id: 'ast-pune',
    name: 'Pune Office',
    type: 'Office',
    city: 'Pune',
    country: 'India',
    coords: [73.8567, 18.5204],
    criticality: 'medium',
    radiusKm: 15,
  },
  {
    id: 'ast-ggm',
    name: 'Gurugram HQ',
    type: 'Office',
    city: 'Gurugram',
    country: 'India',
    coords: [77.0266, 28.4595],
    criticality: 'high',
    radiusKm: 20,
  },
  {
    id: 'ast-che',
    name: 'Chennai Plant',
    type: 'Plant',
    city: 'Chennai',
    country: 'India',
    coords: [80.2707, 13.0827],
    criticality: 'medium',
    radiusKm: 30,
  },
  {
    id: 'ast-lon',
    name: 'London Office',
    type: 'Office',
    city: 'London',
    country: 'United Kingdom',
    coords: [-0.1278, 51.5074],
    criticality: 'low',
    radiusKm: 12,
  },
  {
    id: 'ast-sin',
    name: 'Singapore Hub',
    type: 'Office',
    city: 'Singapore',
    country: 'Singapore',
    coords: [103.8198, 1.3521],
    criticality: 'medium',
    radiusKm: 15,
  },
  {
    id: 'ast-dxb',
    name: 'Dubai Logistics',
    type: 'Warehouse',
    city: 'Dubai',
    country: 'UAE',
    coords: [55.2708, 25.2048],
    criticality: 'high',
    radiusKm: 20,
  },
  ...DEUTSCHE_HQ,
]

const hoursAgo = (h) => Date.now() - h * 3600 * 1000
const daysAhead = (d) => Date.now() + d * 86400 * 1000

export const EVENTS = [
  {
    id: 'ev-flood-mum',
    kind: 'flood',
    category: 'environmental',
    domain: 'Environmental',
    title: 'Flash flooding across central Mumbai after extreme rainfall',
    summary:
      'BMC issued a red alert as several arterial roads and the warehouse district near Andheri East reported knee-deep water. Local rail slowdowns and last-mile trucking delays are expected through the evening tide cycle.',
    place: 'Mumbai, Maharashtra, India',
    flag: 'IN',
    coords: [72.869, 19.089],
    severity: 'high',
    source: 'The Times of India',
    sourceUrl: 'https://timesofindia.indiatimes.com/india',
    publishedAt: hoursAgo(0.3),
    eventAt: hoursAgo(0.4),
    why: 'Last-mile trucks held at the Mumbai Warehouse gate.',
    updates: [
      { at: hoursAgo(0.4), text: 'Red alert · Andheri East ponding' },
      { at: hoursAgo(0.25), text: 'Last-mile trucks held at the warehouse gate' },
    ],
  },
  {
    id: 'ev-fire-thane',
    kind: 'fire',
    category: 'security',
    domain: 'Critical Infrastructure',
    title: 'Industrial fire at chemical godown, Thane–Bhiwandi corridor',
    summary:
      'A warehouse fire is burning in the Bhiwandi logistics belt. Plumes visible from the Mumbai–Nashik highway. Fire services on scene; adjacent storage of packaging solvents raises secondary-blast risk.',
    place: 'Bhiwandi, Maharashtra, India',
    flag: 'IN',
    coords: [72.91, 19.118],
    severity: 'high',
    source: 'Hindustan Times',
    sourceUrl: 'https://www.hindustantimes.com/cities/mumbai-news',
    publishedAt: hoursAgo(0.15),
    eventAt: hoursAgo(0.2),
    why: 'Downwind plume toward the warehouse belt — secondary-blast watch.',
    updates: [
      { at: hoursAgo(0.2), text: 'Plume visible from Mumbai–Nashik highway' },
      { at: hoursAgo(0.12), text: 'Solvent bays adjacent · secondary-blast watch' },
    ],
  },
  {
    id: 'ev-protest-nsk',
    kind: 'protest',
    category: 'geopolitical',
    domain: 'Civil Disturbance',
    title: 'Farmers’ rally occupies Nashik ring road; isolated roadblocks',
    summary:
      'A planned demonstration remains several hundred kilometres from registered Mumbai assets. Traffic disruption is local. No spillover toward Pune or Mumbai reported.',
    place: 'Nashik, Maharashtra, India',
    flag: 'IN',
    coords: [73.7898, 19.9975],
    severity: 'medium',
    source: 'Reuters',
    sourceUrl: 'https://www.reuters.com/world/',
    publishedAt: hoursAgo(1.1),
    eventAt: hoursAgo(1.4),
    why: 'Local roadblocks only — no spillover toward Mumbai or Pune assets.',
  },
  {
    id: 'ev-storm-che',
    kind: 'storm',
    category: 'environmental',
    domain: 'Natural Disasters',
    title: 'Bay cyclone bands: high wind and surge watch for Chennai coast',
    summary:
      'IMD yellow-to-orange upgrade for northern Tamil Nadu. Port operations may slow. Plant perimeter drainage should be inspected; contractor night shifts likely cancelled.',
    place: 'Chennai, Tamil Nadu, India',
    flag: 'IN',
    coords: [80.29, 13.1],
    severity: 'high',
    source: 'Reuters',
    sourceUrl: 'https://www.reuters.com/world/',
    publishedAt: hoursAgo(2.2),
    eventAt: hoursAgo(2.5),
    why: 'Inspect Chennai Plant drainage; night contractor shifts likely cancelled.',
  },
  {
    id: 'ev-sec-ggm',
    kind: 'security',
    category: 'security',
    domain: 'Crime',
    title: 'Armed robbery attempt on cash-in-transit van, MG Road corridor',
    summary:
      'Haryana Police reported shots fired during a CIT intercept near DLF. Perimeter security at nearby campuses elevated. No casualties confirmed at time of filing.',
    place: 'Gurugram, Haryana, India',
    flag: 'IN',
    coords: [77.072, 28.47],
    severity: 'high',
    source: 'Reuters',
    sourceUrl: 'https://www.reuters.com/world/',
    publishedAt: hoursAgo(0.7),
    eventAt: hoursAgo(0.85),
    why: 'Gurugram HQ perimeters raised after shots fired on the CIT corridor.',
    updates: [{ at: hoursAgo(0.7), text: 'Campus perimeters raised · no casualties filed' }],
  },
  {
    id: 'ev-quake-tky',
    kind: 'quake',
    category: 'environmental',
    domain: 'Natural Disasters',
    title: 'M5.4 tremor felt across Kanto; no tsunami advisory',
    summary:
      'JMA reports a moderate inland event. Transport briefly paused then resumed. No ATOM assets in radius. Logged for regional awareness only.',
    place: 'Tokyo, Japan',
    flag: 'JP',
    coords: [139.6917, 35.6895],
    severity: 'medium',
    source: 'Reuters',
    sourceUrl: 'https://www.reuters.com/world/',
    publishedAt: hoursAgo(4),
    eventAt: hoursAgo(4.2),
    why: 'No ATOM site in radius — regional awareness only.',
  },
  {
    id: 'ev-unrest-ist',
    kind: 'protest',
    category: 'geopolitical',
    domain: 'Civil Disturbance',
    title: 'Night demonstrations near Taksim after court ruling',
    summary:
      'Crowd size several thousand. Tear gas reported on Istiklal. No registered ATOM sites in Turkey in this POC set.',
    place: 'Istanbul, Türkiye',
    flag: 'TR',
    coords: [28.9784, 41.0082],
    severity: 'medium',
    source: 'Reuters',
    sourceUrl: 'https://www.reuters.com/world/',
    publishedAt: hoursAgo(3.3),
    eventAt: hoursAgo(3.5),
    why: 'No registered ATOM site in Turkey in this POC set.',
  },
  {
    id: 'ev-haze-sin',
    kind: 'haze',
    category: 'environmental',
    domain: 'Environment',
    title: 'Transboundary haze: PSI climbing through moderate band',
    summary:
      'NEA notes smoke from regional burning. Outdoor work restrictions may follow if PSI crosses unhealthy. Hub operations indoor-normal.',
    place: 'Singapore',
    flag: 'SG',
    coords: [103.82, 1.36],
    severity: 'low',
    source: 'Reuters',
    sourceUrl: 'https://www.reuters.com/world/',
    publishedAt: hoursAgo(5),
    eventAt: hoursAgo(5),
    why: 'Singapore Hub indoor-normal; outdoor holds if PSI turns unhealthy.',
  },
  {
    id: 'ev-strike-lon',
    kind: 'protest',
    category: 'geopolitical',
    domain: 'Political',
    title: 'Rail union overtime ban — 48-hour disruption from Friday',
    summary:
      'Planned industrial action. London office commute impact medium; facility itself not a target. Forecast item.',
    place: 'London, United Kingdom',
    flag: 'GB',
    coords: [-0.12, 51.51],
    severity: 'medium',
    source: 'Reuters',
    sourceUrl: 'https://www.reuters.com/world/',
    publishedAt: hoursAgo(6),
    eventAt: daysAhead(2),
    forecast: true,
    why: 'Forecast commute hit for London Office — facility is not a target.',
  },
  {
    id: 'ev-flood-dxb',
    kind: 'flood',
    category: 'environmental',
    domain: 'Natural Disasters',
    title: 'Short-burst flooding on Sheikh Zayed after cloudburst',
    summary:
      'NCM warned of isolated cells. Underpasses ponding. Logistics gate delays 45–90 minutes during peak.',
    place: 'Dubai, UAE',
    flag: 'AE',
    coords: [55.274, 25.197],
    severity: 'medium',
    source: 'Reuters',
    sourceUrl: 'https://www.reuters.com/world/',
    publishedAt: hoursAgo(1.8),
    eventAt: hoursAgo(2),
    why: 'Dubai Logistics gate delays 45–90 minutes while underpasses pond.',
  },
  {
    id: 'ev-fire-cal',
    kind: 'fire',
    category: 'environmental',
    domain: 'Natural Disasters',
    title: 'Wildfire complex spreading in dry canyon country',
    summary:
      'Containment 20%. No ATOM assets in western US in this sample register. Displayed on geographical feed only.',
    place: 'Riverside County, California, USA',
    flag: 'US',
    coords: [-116.97, 33.74],
    severity: 'high',
    source: 'Reuters',
    sourceUrl: 'https://www.reuters.com/world/',
    publishedAt: hoursAgo(8),
    eventAt: hoursAgo(9),
    why: 'No western-US ATOM asset in this sample — Geo feed only.',
  },
  {
    id: 'ev-rally-pune',
    kind: 'protest',
    category: 'geopolitical',
    domain: 'Civil Disturbance',
    title: 'Student march notified for FC Road — weekend window',
    summary:
      'Police have issued a procession licence. Route passes 2.1 km from Pune Office. Low violence history; traffic and access control are the issues.',
    place: 'Pune, Maharashtra, India',
    flag: 'IN',
    coords: [73.841, 18.531],
    severity: 'low',
    source: 'Reuters',
    sourceUrl: 'https://www.reuters.com/world/',
    publishedAt: hoursAgo(9),
    eventAt: daysAhead(1),
    forecast: true,
    why: 'Licensed march passes 2.1 km from Pune Office — traffic and access, not violence.',
  },
  {
    id: 'ev-protest-fra',
    kind: 'protest',
    category: 'geopolitical',
    domain: 'Civil Disturbance',
    title: 'Climate march on Taunusanlage — Bankenviertel traffic held',
    summary:
      'A licensed procession is moving past the Twin Towers. Police have closed lanes on Mainzer Landstraße. Deutsche Bank Frankfurt HQ sits inside the disruption radius.',
    place: 'Frankfurt am Main, Germany',
    flag: 'DE',
    coords: [8.6752, 50.1124],
    severity: 'medium',
    source: 'Reuters',
    sourceUrl: 'https://www.reuters.com/world/',
    publishedAt: hoursAgo(0.5),
    eventAt: hoursAgo(0.55),
    why: 'Frankfurt HQ sits inside the Bankenviertel disruption radius.',
  },
  {
    id: 'ev-flood-nyc',
    kind: 'flood',
    category: 'environmental',
    domain: 'Natural Disasters',
    title: 'Coastal flood watch — Midtown and Columbus Circle',
    summary:
      'NWS has a coastal flood watch for the next tide cycle. Pedestrian access around Deutsche Bank Center may slow. Forecast item for the New York HQ fence.',
    place: 'Manhattan, New York, USA',
    flag: 'US',
    coords: [-73.984, 40.7672],
    severity: 'medium',
    source: 'Reuters',
    sourceUrl: 'https://www.reuters.com/world/',
    publishedAt: hoursAgo(3),
    eventAt: daysAhead(1),
    forecast: true,
    why: 'Forecast pedestrian slowdown at Deutsche Bank Center next tide cycle.',
  },
]

export const INCOMING = [
  {
    threadId: 'ev-flood-mum',
    text: 'Sion subway closed · evening tide still rising',
  },
  {
    threadId: 'ev-fire-thane',
    text: 'Downwind plume toward the warehouse belt · 6 km',
  },
  {
    id: 'ev-live-kochi',
    kind: 'flood',
    category: 'environmental',
    domain: 'Natural Disasters',
    title: 'Water overtopping bunds along Kochi backwaters',
    summary: 'Local administration reports sluice overflow. No ATOM asset inside radius; logged on geographical feed.',
    why: 'No ATOM asset inside radius — log on Geographical only.',
    place: 'Kochi, Kerala, India',
    flag: 'IN',
    coords: [76.2673, 9.9312],
    severity: 'medium',
    source: 'Reuters',
    sourceUrl: 'https://www.reuters.com/world/',
    publishedAt: Date.now(),
    eventAt: Date.now(),
  },
  {
    id: 'ev-live-dxb-sec',
    kind: 'security',
    category: 'security',
    domain: 'Crime',
    title: 'Cargo-yard intrusion attempt, Jebel Ali free zone',
    summary: 'Perimeter alarm then visual confirm. Patrol intercept. Dubai Logistics sits 11 km north — watchlist.',
    why: 'Dubai Logistics sits 11 km north — watch the fence.',
    place: 'Jebel Ali, Dubai, UAE',
    flag: 'AE',
    coords: [55.027, 24.985],
    severity: 'high',
    source: 'Reuters',
    sourceUrl: 'https://www.reuters.com/world/',
    publishedAt: Date.now(),
    eventAt: Date.now(),
  },
  {
    id: 'ev-live-del',
    kind: 'haze',
    category: 'environmental',
    domain: 'Environment',
    title: 'AQI spike after stubble plume, NCR western corridor',
    summary: 'Hourly AQI crossing 320 at a roadside station. Gurugram HQ indoor-normal; outdoor contractor holds.',
    why: 'Gurugram HQ indoor-normal; hold outdoor contractors.',
    place: 'Gurugram, Haryana, India',
    flag: 'IN',
    coords: [77.04, 28.47],
    severity: 'medium',
    source: 'Reuters',
    sourceUrl: 'https://www.reuters.com/world/',
    publishedAt: Date.now(),
    eventAt: Date.now(),
  },
]

/** Rough Andheri–BKC inundation blob for the Mumbai flood demo (not official hydrology). */
export const MUMBAI_FLOOD_ZONE = {
  type: 'Feature',
  properties: { id: 'zone-flood-mum', name: 'Central Mumbai inundation' },
  geometry: {
    type: 'Polygon',
    coordinates: [
      [
        [72.848, 19.118],
        [72.872, 19.128],
        [72.896, 19.118],
        [72.908, 19.098],
        [72.902, 19.072],
        [72.882, 19.058],
        [72.858, 19.062],
        [72.842, 19.082],
        [72.848, 19.118],
      ],
    ],
  },
}

export const DEMO = {
  eventId: 'ev-flood-mum',
  assetId: 'ast-mum-wh',
}
