export const DESK_BEATS = [
  {
    at: 0,
    cue: 'Critical event pulse over Mumbai',
    mapMode: 'globe',
    pulse: true,
    brief: false,
  },
  {
    at: 1600,
    cue: 'Select the event',
    select: true,
    pulse: true,
    brief: false,
  },
  {
    at: 3200,
    cue: 'Camera zooms into terrain',
    mapMode: 'map',
    pulse: false,
    brief: false,
  },
  {
    at: 5400,
    cue: 'Flood boundary appears',
    flood: true,
    brief: false,
  },
  {
    at: 7200,
    cue: 'Warehouse becomes highlighted',
    warehouse: true,
    brief: false,
  },
  {
    at: 8800,
    cue: 'Event-to-asset distance appears',
    distance: true,
    brief: false,
  },
  {
    at: 10400,
    cue: 'High impact is calculated',
    scoring: true,
    brief: false,
  },
  {
    at: 13600,
    cue: 'Alert and explanation panel opens',
    scoring: false,
    brief: true,
    alerts: true,
  },
  { at: 17000, cue: null },
]
